{
 "title": "System monitoring",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Control image",
   "type": "text",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "options": {
    "content": "![img](http://34.133.13.235:8089/tmp/birdbox-ctrl.jpg?auth=0c67f927f66b92c6dc8dde9867d23d7a)"
   }
  },
  {
   "title": "Infra-red image",
   "type": "text",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 0 },
   "options": {
    "content": "![img](http://34.133.13.235:8089/tmp/birdbox-ir.jpg?auth=0c67f927f66b92c6dc8dde9867d23d7a \"\")"
   }
  },
  {
   "title": "RPi 4B",
   "type": "text",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 0 },
   "options": {
    "content": "![img](http://34.133.13.235:8089/tmp/pi4b.jpg?auth=0c67f927f66b92c6dc8dde9867d23d7a)"
   }
  },
  {
   "title": "Birdbox - temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temp_measurement\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"Warsaw\")\r\n  |> filter(fn: (r) => r[\"machine_name\"] == \"birdbox-ctrl\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"temperature\")"
    }
   ]
  },
  {
   "title": "Birdbox - humidity",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"humidity_measurement\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"Warsaw\")\r\n  |> filter(fn: (r) => r[\"machine_name\"] == \"birdbox-ctrl\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"humidity\")"
    }
   ]
  },
  {
   "title": "Volume level",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "query": "from(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"max_volume_level\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"audio_analysis\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"Warsaw\")\r\n  |> filter(fn: (r) => r[\"machine_name\"] == \"birdbox-ctrl\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> yield(name: \"max\")\r\n  \r\n\r\nfrom(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"volume_level\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"audio_analysis\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"Warsaw\")\r\n  |> filter(fn: (r) => r[\"machine_name\"] == \"birdbox-ctrl\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"level\")\r\n\r\nfrom(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"min_volume_level\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"audio_analysis\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"Warsaw\")\r\n  |> filter(fn: (r) => r[\"machine_name\"] == \"birdbox-ctrl\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: min, createEmpty: false)\r\n  |> yield(name: \"min\")\r\n\r\nfrom(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mean_volume_level\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"audio_analysis\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"Warsaw\")\r\n  |> filter(fn: (r) => r[\"machine_name\"] == \"birdbox-ctrl\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Birdbox temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temp_measurement\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"Warsaw\")\r\n  |> filter(fn: (r) => r[\"machine_name\"] == \"birdbox-ctrl\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"temperature\")\r\n"
    }
   ]
  },
  {
   "title": "Birdbox humidity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"humidity_measurement\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"Warsaw\")\r\n  |> filter(fn: (r) => r[\"machine_name\"] == \"birdbox-ctrl\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"humidity\")"
    }
   ]
  },
  {
   "title": "Volume pressure",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "query": "from(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"volume_pressure\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"audio_analysis\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"Warsaw\")\r\n  |> filter(fn: (r) => r[\"machine_name\"] == \"birdbox-ctrl\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> yield(name: \"volume_pressure\")"
    }
   ]
  },
  {
   "title": "RaspberryPi - cpu_temperature",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_measurement\")\r\n  |> filter(fn: (r) => r[\"machine_name\"] == \"birdbox-ir\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> yield(name: \"birdbox-ir\")\r\n\r\nfrom(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_measurement\")\r\n  |> filter(fn: (r) => r[\"machine_name\"] == \"birdbox-ctrl\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> yield(name: \"birdbox-ctrl\")\r\n\r\nfrom(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_measurement\")\r\n  |> filter(fn: (r) => r[\"machine_name\"] == \"pi4b\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> yield(name: \"pi4b\")"
    },
    { "target": [ "sun_altitude" ] }
   ]
  },
  {
   "title": "Light level",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "query": "from(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"light_level\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"image_analysis\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"Warsaw\")\r\n  |> filter(fn: (r) => r[\"machine_name\"] == \"birdbox-ctrl\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> yield(name: \"birdbox-ctrl\")\r\n\r\nfrom(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"light_level\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"image_analysis\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"Warsaw\")\r\n  |> filter(fn: (r) => r[\"machine_name\"] == \"pi4b\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> yield(name: \"pi4b\")\r\n\r\n\r\nfrom(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"light_level\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"image_analysis\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"Warsaw\")\r\n  |> filter(fn: (r) => r[\"machine_name\"] == \"birdbox-ir\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> yield(name: \"birdbox-ir\")\r\n\r\n"
    },
    { "target": [ "sun_altitude" ] }
   ]
  },
  {
   "title": "birdbox-ctrl - CPU Frequency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "targets": [
    {
     "query": "from(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"frequency\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\r\n  |> filter(fn: (r) => r[\"machine_name\"] == \"birdbox-ctrl\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"freq\")\r\n"
    }
   ]
  },
  {
   "title": "birdbox-ir- CPU Frequency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "targets": [
    {
     "query": "from(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"frequency\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\r\n  |> filter(fn: (r) => r[\"machine_name\"] == \"birdbox-ir\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"freq\")\r\n"
    }
   ]
  },
  {
   "title": "pi4b - CPU Frequency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "targets": [
    {
     "query": "from(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"frequency\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\r\n  |> filter(fn: (r) => r[\"machine_name\"] == \"pi4b\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"freq\")\r\n"
    }
   ]
  }
 ]
}