{
 "title": "System monitoring",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "birdbox-ctrl - timelapse",
   "type": "text",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "options": {
    "content": "\r\n<a target=\"_blank\" href=\"http://34.133.13.235:8089/download/birdbox-ctrl_24_timelapse.mp4?auth_code=0c67f927f66b92c6dc8dde9867d23d7a\">LINK</a>\r\n"
   }
  },
  {
   "title": "birdbox-ir - timelapse",
   "type": "text",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 0 },
   "options": {
    "content": "\r\n<a target=\"_blank\" href=\"http://34.133.13.235:8089/download/birdbox-ir_24_timelapse.mp4?auth_code=0c67f927f66b92c6dc8dde9867d23d7a\">LINK</a>\r\n"
   }
  },
  {
   "title": "RPi 4B - timelapse",
   "type": "text",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 0 },
   "options": {
    "content": "\r\n<a target=\"_blank\" href=\"http://34.133.13.235:8089/download/pi4b_24_timelapse.mp4?auth_code=0c67f927f66b92c6dc8dde9867d23d7a\">LINK</a>\r\n"
   }
  },
  {
   "title": "RPi 2B - timelapse",
   "type": "text",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "options": {
    "content": "\r\n<a target=\"_blank\" href=\"http://34.133.13.235:8089/download/pi2b_24_timelapse.mp4?auth_code=0c67f927f66b92c6dc8dde9867d23d7a\">LINK</a>\r\n"
   }
  },
  {
   "title": "birdbox-ctrl - motion detection",
   "type": "text",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 10 },
   "options": {
    "content": "<div>\r\n<video width=\"100%\" height=\"100%\" src=\"http://34.133.13.235:8089/download/vid_segment_short_birdbox-ctrl.mp4?auth_code=0c67f927f66b92c6dc8dde9867d23d7a\"></video>\r\n</div>\r\n<br/>\r\n<a target=\"_blank\" href=\"http://34.133.13.235:8089/download/vid_segment_short_birdbox-ctrl.mp4?auth_code=0c67f927f66b92c6dc8dde9867d23d7a\">LINK</a>\r\n"
   }
  },
  {
   "title": "birdbox-ir - motion detection",
   "type": "text",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 10 },
   "options": {
    "content": "<div>\r\n<video width=\"100%\" height=\"100%\" src=\"http://34.133.13.235:8089/download/vid_segment_short_birdbox-ir.mp4?auth_code=0c67f927f66b92c6dc8dde9867d23d7a\"></video>\r\n</div>\r\n<br/>\r\n<a target=\"_blank\" href=\"http://34.133.13.235:8089/download/vid_segment_short_birdbox-ir.mp4?auth_code=0c67f927f66b92c6dc8dde9867d23d7a\">LINK</a>\r\n"
   }
  },
  {
   "title": "RPi 4B - motion detection",
   "type": "text",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 10 },
   "options": {
    "content": "<div>\r\n<video width=\"100%\" height=\"100%\" src=\"http://34.133.13.235:8089/download/vid_segment_short_pi4b.mp4?auth_code=0c67f927f66b92c6dc8dde9867d23d7a\"></video>\r\n</div>\r\n<br/>\r\n<a target=\"_blank\" href=\"http://34.133.13.235:8089/download/vid_segment_short_pi4b.mp4?auth_code=0c67f927f66b92c6dc8dde9867d23d7a\">LINK</a>\r\n"
   }
  },
  {
   "title": "RPi 2B - motion detection",
   "type": "text",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 10 },
   "options": {
    "content": "<div>\r\n<video width=\"100%\" height=\"100%\" src=\"http://34.133.13.235:8089/download/vid_segment_short_pi2b.mp4?auth_code=0c67f927f66b92c6dc8dde9867d23d7a\"></video>\r\n</div>\r\n<br/>\r\n<a target=\"_blank\" href=\"http://34.133.13.235:8089/download/vid_segment_short_pi2b.mp4?auth_code=0c67f927f66b92c6dc8dde9867d23d7a\">LINK</a>\r\n"
   }
  },
  {
   "title": "Control image",
   "type": "text",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 20 },
   "options": {
    "content": "![img](http://34.133.13.235:8089/download/birdbox-ctrl.jpg?auth_code=0c67f927f66b92c6dc8dde9867d23d7a)\r\n<a target=\"_blank\" href=\"http://34.133.13.235:8089/download/birdbox-ctrl.jpg?auth_code=0c67f927f66b92c6dc8dde9867d23d7a\">LINK</a>"
   }
  },
  {
   "title": "Infra-red image",
   "type": "text",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 20 },
   "options": {
    "content": "![img](http://34.133.13.235:8089/download/birdbox-ir.jpg?auth_code=0c67f927f66b92c6dc8dde9867d23d7a)\r\n<a target=\"_blank\" href=\"http://34.133.13.235:8089/download/birdbox-ir.jpg?auth_code=0c67f927f66b92c6dc8dde9867d23d7a\">LINK</a>"
   }
  },
  {
   "title": "RPi 4B",
   "type": "text",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 20 },
   "options": {
    "content": "![img](http://34.133.13.235:8089/download/pi4b.jpg?auth_code=0c67f927f66b92c6dc8dde9867d23d7a)\r\n<a target=\"_blank\" href=\"http://34.133.13.235:8089/download/pi4b.jpg?auth_code=0c67f927f66b92c6dc8dde9867d23d7a\">LINK</a>\r\n"
   }
  },
  {
   "title": "RPi 2B",
   "type": "text",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 20 },
   "options": {
    "content": "![img](http://34.133.13.235:8089/download/pi2b.jpg?auth_code=0c67f927f66b92c6dc8dde9867d23d7a)\r\n<a target=\"_blank\" href=\"http://34.133.13.235:8089/download/pi2b.jpg?auth_code=0c67f927f66b92c6dc8dde9867d23d7a\">LINK</a>\r\n"
   }
  },
  {
   "title": "Control image",
   "type": "text",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 30 },
   "options": {
    "content": "![img](http://34.133.13.235:8089/download/birdbox-ctrl_24.jpg?auth_code=0c67f927f66b92c6dc8dde9867d23d7a)\r\n<a target=\"_blank\" href=\"http://34.133.13.235:8089/download/birdbox-ctrl_24.jpg?auth_code=0c67f927f66b92c6dc8dde9867d23d7a\">LINK</a>"
   }
  },
  {
   "title": "Infra-red image",
   "type": "text",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 30 },
   "options": {
    "content": "![img](http://34.133.13.235:8089/download/birdbox-ir_24.jpg?auth_code=0c67f927f66b92c6dc8dde9867d23d7a)\r\n<a target=\"_blank\" href=\"http://34.133.13.235:8089/download/birdbox-ir_24.jpg?auth_code=0c67f927f66b92c6dc8dde9867d23d7a\">LINK</a>"
   }
  },
  {
   "title": "RPi 4B",
   "type": "text",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 30 },
   "options": {
    "content": "![img](http://34.133.13.235:8089/download/pi4b_24.jpg?auth_code=0c67f927f66b92c6dc8dde9867d23d7a)\r\n<a target=\"_blank\" href=\"http://34.133.13.235:8089/download/pi4b_24.jpg?auth_code=0c67f927f66b92c6dc8dde9867d23d7a\">LINK</a>"
   }
  },
  {
   "title": "RPi 2B",
   "type": "text",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 30 },
   "options": {
    "content": "![img](http://34.133.13.235:8089/download/pi2b_24.jpg?auth_code=0c67f927f66b92c6dc8dde9867d23d7a)\r\n<a target=\"_blank\" href=\"http://34.133.13.235:8089/download/pi2b_24.jpg?auth_code=0c67f927f66b92c6dc8dde9867d23d7a\">LINK</a>"
   }
  },
  {
   "title": "Birdbox - temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temp_measurement\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"machine_name\"] == \"birdbox-ctrl\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"temperature\")"
    }
   ]
  },
  {
   "title": "Birdbox - humidity",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"humidity_measurement\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\r\n  |> filter(fn: (r) => r[\"machine_name\"] == \"birdbox-ctrl\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"humidity\")"
    }
   ]
  },
  {
   "title": "Volume level",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "query": "from(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"max_volume_level\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"audio_analysis\")\r\n  |> filter(fn: (r) => r[\"machine_name\"] == \"birdbox-ctrl\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> yield(name: \"max\")\r\n  \r\n\r\nfrom(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"volume_level\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"audio_analysis\")\r\n  |> filter(fn: (r) => r[\"machine_name\"] == \"birdbox-ctrl\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"level\")\r\n\r\nfrom(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"min_volume_level\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"audio_analysis\")\r\n  |> filter(fn: (r) => r[\"machine_name\"] == \"birdbox-ctrl\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: min, createEmpty: false)\r\n  |> yield(name: \"min\")\r\n\r\nfrom(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mean_volume_level\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"audio_analysis\")\r\n  |> filter(fn: (r) => r[\"machine_name\"] == \"birdbox-ctrl\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Birdbox temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temp_measurement\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"machine_name\"] == \"birdbox-ctrl\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"temperature\")\r\n"
    }
   ]
  },
  {
   "title": "Birdbox humidity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"humidity_measurement\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\r\n  |> filter(fn: (r) => r[\"machine_name\"] == \"birdbox-ctrl\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"humidity\")"
    }
   ]
  },
  {
   "title": "Volume pressure",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "query": "from(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"volume_pressure\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"audio_analysis\")\r\n  |> filter(fn: (r) => r[\"machine_name\"] == \"birdbox-ctrl\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> yield(name: \"volume_pressure\")"
    }
   ]
  },
  {
   "title": "Scale",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"scale\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"scale\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> yield(name: \"max\")\r\n  "
    }
   ]
  },
  {
   "title": "Light level",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "query": "from(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"light_level\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"image_analysis\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> yield()\r\n"
    },
    { "target": [ "sun_altitude" ] }
   ]
  },
  {
   "title": "RaspberryPi - cpu_temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_measurement\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> yield()\r\n"
    },
    { "target": [ "sun_altitude" ] }
   ]
  },
  {
   "title": "RaspberryPi - restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"restart\")\r\n  |> filter(fn: (r) => r[\"machine_name\"] == \"birdbox-ir\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> yield(name: \"birdbox-ir\")\r\n\r\nfrom(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"restart\")\r\n  |> filter(fn: (r) => r[\"machine_name\"] == \"birdbox-ctrl\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> yield(name: \"birdbox-ctrl\")\r\n\r\nfrom(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"restart\")\r\n  |> filter(fn: (r) => r[\"machine_name\"] == \"pi4b\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> yield(name: \"pi4b\")"
    }
   ]
  },
  {
   "title": "birdbox-ctrl - CPU Frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "targets": [
    {
     "query": "from(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"frequency\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\r\n  |> filter(fn: (r) => r[\"machine_name\"] == \"birdbox-ctrl\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"freq\")\r\n"
    }
   ]
  },
  {
   "title": "birdbox-ir- CPU Frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "targets": [
    {
     "query": "from(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"frequency\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\r\n  |> filter(fn: (r) => r[\"machine_name\"] == \"birdbox-ir\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"freq\")\r\n"
    }
   ]
  },
  {
   "title": "pi4b - CPU Frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "targets": [
    {
     "query": "from(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"frequency\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\r\n  |> filter(fn: (r) => r[\"machine_name\"] == \"pi4b\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"freq\")\r\n"
    }
   ]
  },
  {
   "title": "pi2b - CPU Frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "targets": [
    {
     "query": "from(bucket: \"main\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"frequency\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\r\n  |> filter(fn: (r) => r[\"machine_name\"] == \"pi2b\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"freq\")\r\n"
    }
   ]
  }
 ]
}